@startuml
class Building {
    - healthSystem : HealthSystem
    - buildingType : BuildingTypeSO
    - buildingDemolishBtn : Transform
    - buildingRepairBtn : Transform
    - Start() : void
    - Building_onHeal(sender:object, e:EventArgs) : void
    - Building_OnDamage(sender:object, e:EventArgs) : void
    - Building_OnDie(sender:object, e:EventArgs) : void
    - OnMouseEnter() : void
    - OnMouseExit() : void
    - ShowDemolishBtn() : void
    - HideDemolishBtn() : void
    - ShowRepairBtn() : void
    - HideRepairBtn() : void
}
MonoBehaviour <|-- Building
@enduml
