@startuml
class BuildingTypeSelectUi {
    - arrowSprite : Sprite
    - btnTemplateUI : GameObject
    - arrowbtn : GameObject
    - btnTransformDictionary : Dictionary<BuildingTypeSO ,Transform>
    - ignoreBuildingTypeList : List<BuildingTypeSO>
    - Awake() : void
    - Start() : void
    - BuildingManager_OnActiveBuildingTypeBuildingChanged(sender:object, e:BuildingManager.OnActiveTypeBuildingChangeEventArgs) : void
    - AvtiveBuildingTypeButton() : void
}
MonoBehaviour <|-- BuildingTypeSelectUi
@enduml
