@startuml
class BuildingConstruction {
    + {static} Create(position:Vector3, bulidingType:BuildingTypeSO) : BuildingConstruction
    - construstionTimer : float
    - construstionTimerMax : float
    - buildingType : BuildingTypeSO
    - boxCollider2D : BoxCollider2D
    - spriteRenderer : SpriteRenderer
    - buildingTypeHolder : BuildingTypeHolder
    - constructionMaterial : Material
    - Awake() : void
    - Update() : void
    - SetUp(buildingType:BuildingTypeSO) : void
    + GetConstrustionTimerNormalized() : float
}
MonoBehaviour <|-- BuildingConstruction
@enduml
