@startuml
class Emeny {
    + {static} Create(position:Vector3) : Emeny
    - targetTransfrom : Transform
    - rigidbody2D : Rigidbody2D
    - healthSystem : HealthSystem
    - lookForTimer : float
    - maxlookforTimer : float = 0.2f
    - Awake() : void
    - Start() : void
    - Emeny_OnDamage(sender:object, e:System.EventArgs) : void
    - Emeny_OnDie(sender:object, e:System.EventArgs) : void
    - Update() : void
    - OnCollisionEnter2D(other:Collision2D) : void
    - HandleMovement() : void
    - HandleTargeting() : void
    - LookForIt() : void
}
MonoBehaviour <|-- Emeny
@enduml
