@startuml
class EnemyWaveUI {
    - nextWaveText : TextMeshProUGUI
    - waveTimerText : TextMeshProUGUI
    - enemyWaveManager : EnemyWaveManager
    - spwanPointIndicator : RectTransform
    - enemyIncomingIndicator : RectTransform
    - mainCamera : Camera
    - Awake() : void
    - Start() : void
    - EmenyWaveManager_OnWaveNumberChange(sender:object, e:EventArgs) : void
    - Update() : void
    - NextWaveMessageHandle() : void
    - HandleNextSpawnPointIndicator() : void
    - HandleEnemyClosed() : void
    - SetMessageText(message:string) : void
    - SetWaveNumberText(message:string) : void
}
MonoBehaviour <|-- EnemyWaveUI
@enduml
