@startuml
class HealthSystem {
    +  <<event>> OnDamaged : EventHandler 
    +  <<event>> OnHeal : EventHandler 
    +  <<event>> OnDie : EventHandler 
    - health : int
    - maxAmountHealth : int
    - Awake() : void
    + Damage(damageAmount:int) : void
    + Heal(healAmount:int) : void
    + HealFull() : void
    + IsFullHealth() : bool
    + IsDead() : bool
    + GetHealthInfo() : int
    + GetHealthMaxInfo() : int
    + GetHealthAmountNormalized() : float
    + SetMaxHealth(maxBuildingHealth:int, UpdateInfo:bool) : void
}
MonoBehaviour <|-- HealthSystem
@enduml
