@startuml
class HealthBar {
    - healthSystem : HealthSystem
    - barTransform : Transform
    - Awake() : void
    - Start() : void
    - HealthBar_OnHeal(sender:object, e:EventArgs) : void
    - HealthBar_OnDamageReceived(sender:object, e:EventArgs) : void
    - UpdateHealthBar() : void
    - HealthBarVisible() : void
}
MonoBehaviour <|-- HealthBar
@enduml
