@startuml
class ResourceGenerator {
    + {static} GetNearByResourceAmount(resourceGenerateData:ResourceGenerateData, position:Vector3) : int
    - timer : float
    - maxTimer : float
    - buildingType : BuildingTypeSO
    - resourceGenerateData : ResourceGenerateData
    - Awake() : void
    - Start() : void
    - Update() : void
    + GetResourceGenerateData() : ResourceGenerateData
    + GetTimerNormalized() : float
    + Get5AmountGeneratorPerSecond() : float
}
MonoBehaviour <|-- ResourceGenerator
@enduml
