@startuml
class ResourcesUI {
    - resourceTemplet : Transform
    - resourceTypeList : ResourceTypeListSO
    - resourceTypeTransformDictonary : Dictionary<ResourceTypeSO, Transform>
    - Awake() : void
    - Start() : void
    - ResourceManager_OnResourceAmountChanged(sender:object, e:EventArgs) : void
    - UpdateResourceAmount() : void
}
MonoBehaviour <|-- ResourcesUI
@enduml
