@startuml
class ResourceNearbyOverlay {
    - resourceGenerateData : ResourceGenerateData
    - Awake() : void
    - Update() : void
    + Show(resourceGenerateData:ResourceGenerateData) : void
    + Hide() : void
}
MonoBehaviour <|-- ResourceNearbyOverlay
@enduml
