@startuml
class ResourceManager {
    + {static} Instance : ResourceManager <<get>>
    +  <<event>> OnResourceAmountChange : EventHandler 
    - resourceAmountDictionary : Dictionary<ResourceTypeSO,int>
    - Awake() : void
    - Update() : void
    - Testing() : void
    + AddResources(resourceType:ResourceTypeSO, amount:int) : void
    + GetResourceAmount(resourceTypeSO:ResourceTypeSO) : int
    + CanAfford(resourceAmountArray:ResourceCostAmount[]) : bool
    + SpendAmount(resourceCostAmounts:ResourceCostAmount[]) : void
}
MonoBehaviour <|-- ResourceManager
@enduml
