@startuml
class Soundmanager {
    + {static} Instance : Soundmanager <<get>>
    - audioSource : AudioSource
    - audioClipDictionary : Dictionary<Sound ,AudioClip>
    - volume : float = 0.5f
    - Awake() : void
    + PlaySound(sound:Sound) : void
    + VolumeIncrease() : void
    + VolumeDecrease() : void
    + GetSoundVolume() : float
}
enum Sound {
    BuildingPlaced,
    GameOver,
    BuildingDestoryed,
    BuildingDamaged,
    EnemyDie,
    EnemyHit,
    EnemyWaveStarting,
}
MonoBehaviour <|-- Soundmanager
Soundmanager +-- Sound
@enduml
