@startuml
class ToolTipUI {
    + {static} Instance : ToolTipUI <<get>>
    - textMeshPro : TextMeshProUGUI
    - backgroundRectTransform : RectTransform
    - rectTransform : RectTransform
    - toolTipTimer : ToolTipTimer
    - canvasRectTransfomr : RectTransform
    - Awake() : void
    - SetText(text:string) : void
    - Update() : void
    - HandleMousePosition() : void
    + Show(toolTipText:string, toolTipTimer:ToolTipTimer) : void
    + Hide() : void
}
class ToolTipTimer {
    + timer : float
}
MonoBehaviour <|-- ToolTipUI
ToolTipUI +-- ToolTipTimer
@enduml
