@startuml
class Tower {
    - shootTimerMax : float
    - shootTimer : float
    - targetEmeny : Emeny
    - timer : float
    - maxTimer : float
    - shootingposition : Vector3
    - Awake() : void
    - Update() : void
    - HandleTragetting() : void
    - Shooting() : void
    - LookAtTarget() : void
}
MonoBehaviour <|-- Tower
@enduml
